// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouRc6Uq3WSe9AK3PwOa5XlvDWLmMjC3A',
    appId: '1:1076012159800:web:53f303274c1091bb8267cd',
    messagingSenderId: '1076012159800',
    projectId: 'flutter-crud-8ff51',
    authDomain: 'flutter-crud-8ff51.firebaseapp.com',
    storageBucket: 'flutter-crud-8ff51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3BSEo6ys3k4tlxy_tT-ErP68kjZByMA',
    appId: '1:1076012159800:android:4830f6f1262f47ae8267cd',
    messagingSenderId: '1076012159800',
    projectId: 'flutter-crud-8ff51',
    storageBucket: 'flutter-crud-8ff51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_OwKv9hBzk77pVrzM4U-AHXKKhez8PtU',
    appId: '1:1076012159800:ios:7fae83e2bbcfdd4f8267cd',
    messagingSenderId: '1076012159800',
    projectId: 'flutter-crud-8ff51',
    storageBucket: 'flutter-crud-8ff51.appspot.com',
    iosClientId: '1076012159800-rklfa0gksd7cu2c3fhgcoqipuv561tek.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_OwKv9hBzk77pVrzM4U-AHXKKhez8PtU',
    appId: '1:1076012159800:ios:702a4c3a235edcbc8267cd',
    messagingSenderId: '1076012159800',
    projectId: 'flutter-crud-8ff51',
    storageBucket: 'flutter-crud-8ff51.appspot.com',
    iosClientId: '1076012159800-n8i9sk41ov7klt9u2hq8jgnlo9n4i4n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
